### ISSUE TITLE
Player doesn't fall when doing a superjump, *sometimes*

### ISSUE THREAD

**Issue by Frostwithasideofsalt** [tylerandari13/Episode-Orange#5]
i know that this is known but im making a issue about it so it wont get forgotten 

https://github.com/tylerandari13/Episode-Orange/assets/60326522/b55d1d34-a989-48d5-8957-b194f39e4c02

**Comment by Frostwithasideofsalt** [comment]
so its actually worse then i thought 
Uploading Episode Orange (DEBUG) 2023-11-13 21-31-45.mp4…

**Comment by tylerandari13** [comment]
> so its actually worse then i thought Uploading Episode Orange (DEBUG) 2023-11-13 21-31-45.mp4…

Uploading Episode Orange (DEBUG) 2023-11-13 21-31-45.mp4…

**Comment by Frostwithasideofsalt** [comment]
i love github

**Comment by tylerandari13** [comment]
https://github.com/tylerandari13/Episode-Orange/assets/118036786/6621869b-81c1-4162-9f56-d29a3aa43256

**Comment by Frostwithasideofsalt** [comment]
yeah thats the issue

**Comment by Frostwithasideofsalt** [comment]
https://cdn.discordapp.com/attachments/831384653100744744/1173858528516116601/Episode_Orange_DEBUG_2023-11-13_21-31-45.mp4?ex=65657bf2&is=655306f2&hm=50eabd6a4627ce8ef21b8c63b774bbae147d56efac479f666d7494738e8dd9e6& the video which failed to upload

**Comment by tylerandari13** [comment]
i think i know what caused this, lemme look into it

**Comment by Frostwithasideofsalt** [comment]
my only guess is that when preparing for a superjump, the gravity gets disabled and the player retains the vertical momentum they had when starting to prepare the superjump

**Comment by tylerandari13** [comment]
it looks like when i did the refactor i forgot to add the line that disables gravity in the first place, this means somehow Orange is ascending even when gravity is on

**Comment by tylerandari13** [comment]
> it looks like when i did the refactor i forgot to add the line that disables gravity in the first place, this means somehow Orange is ascending even when gravity is on

...and somehow forcing it on anyway fixes the issue

**Comment by tylerandari13** [comment]
should be fixed with https://github.com/tylerandari13/Episode-Orange/commit/0eec142e36a1b741fe290eaf7e2b82f1f5ee81e0

**Comment by Frostwithasideofsalt** [comment]
yeah it works properly now
